logging:
  level:
    org:
      hibernate:
        SQL: WARN
        type: WARN
      springframework:
        web: WARN
    root: WARN
server:
  port: 8085
spring:
  datasource:
    dbcp2:
      max-idle: 8
      max-wait-millis: 10000
      min-evictable-idle-time-millis: 1000
      min-idle: 8
      time-between-eviction-runs-millis: 1
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: knowsong
    tomcat:
      max-active: 10
    url: jdbc:mysql://localhost:3306/knowsong?useSSL=false&useLegacyDatetimeCode=false&serverTimezone=MST
    username: knowsong
  jmx:
    default-domain: knowsong
  jpa:
    show-sql: false
  security:
    oauth2:
      client:
        provider:
          spotify:
            authorization-uri: https://accounts.spotify.com/authorize
            token-uri: https://accounts.spotify.com/api/token
            user-info-uri: https://api.spotify.com/v1/me
            user-name-attribute: id
        registration:
          spotify:
            authorization-grant-type: authorization_code

            client-id: hello

            client-name: Spotify
            client-secret: ab88c01f4c3541bdbd238d4bcbae2635
            redirect-uri: '{baseUrl}/login/oauth2/code/{registrationId}'
            scope: user-read-private
